/* eslint-disable no-unused-vars */
export enum ENUM_NOTIFICATION_TYPE {
    CLEANING_PLAN_CREATED = 'CLEANING_PLAN_CREATED',
    CLEANING_PLAN_DELETED = 'CLEANING_PLAN_DELETED',
    LOCATION_DEACTIVATED = 'LOCATION_DEACTIVATED',
    CLIENT_DELETED = 'CLIENT_DELETED',
    ISSUE_REPORT_CREATED = 'ISSUE_REPORT_CREATED',
    ISSUE_REPORT_STATUS_CHANGED = 'ISSUE_REPORT_STATUS_CHANGED',
    ADDITIONAL_TASK_CREATED = 'ADDITIONAL_TASK_CREATED',
    ADDITIONAL_TASK_APPROVED = 'ADDITIONAL_TASK_APPROVED',
    ADDITIONAL_TASK_REJECTED = 'ADDITIONAL_TASK_REJECTED',
    SHIFT_CHECKED_IN = 'SHIFT_CHECKED_IN',
    SHIFT_CHECKED_OUT = 'SHIFT_CHECKED_OUT',
    SHIFT_COMPLETED = 'SHIFT_COMPLETED',
    SHIFT_WORKER_ASSIGNED = 'SHIFT_WORKER_ASSIGNED',
    SHIFT_WORKER_REMOVED = 'SHIFT_WORKER_REMOVED',
    SHIFT_CANCELLED = 'SHIFT_CANCELLED',
    NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',
    SUPPORT_CREATED = 'SUPPORT_CREATED',
    GENERAL = 'GENERAL',
}

export const NOTIFICATION_ACTION = {
    VIEW: 'VIEW',
    LIST: 'LIST',
} as const;

export const NOTIFICATION_ENTITY = {
    CLEANING_PLAN: 'CLEANING_PLAN',
    LOCATION: 'LOCATION',
    ADDITIONAL_TASK: 'ADDITIONAL_TASK',
    SHIFT: 'SHIFT',
    CHAT: 'CHAT',
    CLIENT: 'CLIENT',
    WORKER: 'WORKER',
    SUPPORT: 'SUPPORT',
    ISSUE_REPORT: 'ISSUE_REPORT',
} as const;

export type NOTIFICATION_ENTITY_TYPE =
    (typeof NOTIFICATION_ENTITY)[keyof typeof NOTIFICATION_ENTITY];
